name: room_signals
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

  leto:
  leto_schema:
  leto_shelf:
  valida: ^0.1.0-dev.1
  json_annotation:
  dart_jsonwebtoken: ^2.4.1

dev_dependencies:
  http: ^0.13.0
  lint: ^1.8.2
  test: ^1.15.0
  build_runner:
  json_serializable:
  valida_generator: ^0.1.0-dev.1
  leto_generator:
  room_signals_client:
    path: room_signals_client

dependency_overrides:
  analyzer: ^3.0.0
  gql: ^0.13.1-alpha
