name: room_signals
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

  leto:
  leto_schema:
  leto_shelf:
  valida:
  json_annotation:
  dart_jsonwebtoken: ^2.4.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  build_runner:
  json_serializable:
  valida_generator:
  leto_generator:
  room_signals_client:
    path: room_signals_client

dependency_overrides:
  analyzer: ^3.0.0
  leto_generator:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_generator
      ref: valida_integration
  leto:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto
      ref: valida_integration
  leto_schema:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_schema
      ref: valida_integration
  leto_shelf:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_shelf
      ref: valida_integration
  valida:
    git:
      url: https://github.com/juancastillo0/valida
      path: valida
  valida_generator:
    git:
      url: https://github.com/juancastillo0/valida
      path: valida_generator
