name: room_signals_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  artemis: ^7.9.0-beta
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  gql: ^0.13.1-alpha
  http:
  gql_exec:
  gql_link:
  gql_websocket_link:

dev_dependencies:
  lint: ^1.8.2
  test: ^1.16.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
